name: lint
on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:

jobs:
  golangci:
    name: golangci-lint
    runs-on: ubuntu-latest
    steps:
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
        run: git config --global url."https://kapeta-bot:${TOKEN}@github.com".insteadOf "https://github.com"
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
      - name: golangci-lint
        env:
          GOPRIVATE: github.com/kapetacom/*
        uses: golangci/golangci-lint-action@v3.4.0
        with:
          args: --verbose --timeout=3m
