name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        env:
          GOPRIVATE: github.com/blockwarecom/*
      - name: Configure git for private modules
        env:
          TOKEN: ${{ secrets.BOT_TOKEN }}
        run: |
          git config --global url."https://blockware-bot:${TOKEN}@github.com".insteadOf "https://github.com"
          # fail if go.mod and go.sum are out of sync
          go mod verify
          # download dependencies
          go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
