name: Go package

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod
          cache: true

      - name: Install dependencies
        run: |
          # fail if go.mod and go.sum are out of sync
          go mod verify
          # download dependencies
          go mod download

      - name: Build
        run: go build -v ./...

      - name: Test
        run: go test -v ./...
