name: Docker Publish

on:
  push:
    branches:
      - master
    tags:
      - "v*"
  pull_request:
    branches:
      - 'master'

jobs:
  build:
    permissions:
      contents: 'read'
      id-token: 'write'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Login to image repository
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: kapetacom/insight-api
          flavor: latest=true
          tags: |
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}
            type=semver,pattern={{major}}
            type=sha,format=long,prefix=

      - name: Build and push docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          push: ${{ github.ref_type == 'tag' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          network: host

      - name: checkout action
        uses: actions/checkout@v3
        with:
          repository: kapetacom/core-deploy-action
          path: ./github-action/core-deploy-action
          token: ${{ secrets.GHA_TOKEN }}

      - name: deploy to Kapeta cloud
        uses: ./github-action/core-deploy-action
        env:
          GITHUB_TOKEN: ${{ secrets.GHA_TOKEN }}
        with:
          image: kapetacom/insight-api
          tag: ${{ github.sha }}

